user_manage:
    path: /user/manage
    defaults: { _controller: AppBundle:Default:index }

user_add:
    path: /user/add
    defaults: { _controller: AppBundle:Default:add }

user_delete:
    path: /user/{id}/delete
    defaults: { _controller: AppBundle:Default:delete }

user_update:
    path: /user/{id}/update
    defaults: { _controller: AppBundle:Default:update }